# Generated by Django 3.0.5 on 2021-02-02 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 10, 30, 3, 777828, tzinfo=utc), null=True),
        ),
    ]
