# Generated by Django 3.0.5 on 2021-01-25 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 21, 51, 35, 278377, tzinfo=utc), null=True),
        ),
    ]
