# Generated by Django 3.0.5 on 2021-03-17 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitemlist',
            old_name='stock_market',
            new_name='stock_market_name',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 13, 17, 57, 136528, tzinfo=utc), null=True),
        ),
    ]
