# Generated by Django 3.1.3 on 2020-12-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_item_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_market_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.stockmarket'),
        ),
    ]
