# Generated by Django 3.0.5 on 2021-02-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20210202_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
