# Generated by Django 3.0.5 on 2021-02-02 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_delete_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_item_name', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2021, 2, 2, 10, 38, 38, 268363, tzinfo=utc), null=True)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('adj_close', models.FloatField(default=0.0)),
                ('stock_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.StockMarket')),
            ],
        ),
    ]
