# Generated by Django 3.0.5 on 2021-02-14 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_stockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 14, 9, 24, 41, 67103, tzinfo=utc), null=True),
        ),
    ]
